# Experiment 2: Logistics Regression - IRIS Dataset

**Name:** Arshan Attar  
**Roll Number:** 231408  


## 1. Import Packages

In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

* `numpy` and `pandas` are imported for numerical and data handling.
* `datasets` loads the Iris dataset.
* `train_test_split` divides the dataset into training and testing data.
* `LogisticRegression` creates the classification model.
* The metrics are used to evaluate the model.

## 2. Load the Dataset

In [ ]:
iris = datasets.load_iris()

print(iris.feature_names)
print(iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


* Loads the built-in Iris dataset.
* Prints the names of the input features and the flower classes.
* The input features are sepal length (cm), sepal width (cm), petal length (cm), and petal width (cm).
* The flower classes are setosa, versicolor, and virginica.

## 3. Separate the independent and dependent variables

In [ ]:
#x = iris.data[:, :4]
X = iris.data
Y = iris.target

* `X` contains the input features (Sepal Length, Sepal Width, Petal Length, Petal Width).
* `Y` contains the target classes (Setosa, Versicolor, Virginica).

## 4. Split the data into training and testing sets.

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.3, random_state=1
)

* 70% of the data is used for training.
* 30% of the data is used for testing.
* Using `random_state=1` makes the split reproducible so you get the same results every time.

## 5. Train the model

In [ ]:
classifier = LogisticRegression(random_state=42)

classifier.fit(X_train, Y_train)

LogisticRegression(random_state=42)

* Creates the Logistic Regression model.
* `fit()` trains the model using the training data.

https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier

## 6. Predict the test data set values using the model above

In [ ]:
Y_pred = classifier.predict(X_test)

* Predicts the flower class for each sample in the test dataset.

## 7. Calculate the accuracy of the model using the accuracy score function

In [ ]:
print("Accuracy:", accuracy_score(Y_test, Y_pred) * 100)

print(confusion_matrix(Y_test, Y_pred))

print(classification_report(Y_test, Y_pred))

Accuracy: 97.77777777777777
[[14  0  0]
 [ 0 17  1]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.94      0.97        18
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



* `accuracy_score()` calculates the percentage of correct predictions & it is 97.77.
* `confusion_matrix()` compares actual and predicted classes.
* `classification_report()` displays Precision, Recall, F1-score, and Support.

## 8. Testing of the models

In [ ]:
Test_values = [
    [5.4, 3.0, 4.5, 1.5],
    [5.1, 3.3, 1.7, 0.5],
    [6.0, 2.2, 5.0, 1.5]
]

prediction = classifier.predict(Test_values)

print("Predicted Classes:", prediction)

Predicted Classes: [1 0 2]


* `Test_values` contains three new flower samples.
* `predict()` predicts the class of each sample.
* Output: `[1 0 2]`
* Where: 0 = Setosa, 1 = Versicolor, 2 = Virginica